name: "Build PostmarketOS for MSM89X7"

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        arch: ["aarch64"]
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    container:
      image: zaoqi/archlinux:latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Get current date
      id: date
      run: echo "stamp=$(date '+%s')" >> $GITHUB_ENV
    - name: Install tools
      run: sudo pacman -Sy ; sudo pacman -S python-is-python3 python3-pip git -y
    - name: Install pmbootstrap
      run: git clone https://gitlab.postmarketos.org/postmarketOS/pmbootstrap.git ; cd pmbootstrap ; mkdir -p ~/.local/bin ; ln -s "$PWD/pmbootstrap.py" ~/.local/bin/pmbootstrap
    - name: Create work directory
      run: mkdir -p /home/runner/.local/var/pmbootstrap
    - name: Update pmbootstrap
      run: pmbootstrap -c configs/pmbootstrap.${{ matrix.arch }}.cfg -y -p pmbootstrap/cache_git/pmaports/ pull
    - name: pmbootstrap install
      run: pmbootstrap -c configs/pmbootstrap.${{ matrix.arch }}.cfg -y -p pmbootstrap/cache_git/pmaports/ install --password 1111 --no-sshd
    - name: Zip image
      run: mkdir -p postmarketos-qcom-msm89x7/boot && sudo cp -r /home/runner/.local/var/pmbootstrap/chroot_native/home/pmos/rootfs/qcom-msm89x7.img/ && cp -r /home/runner/.local/var/pmbootstrap/chroot_rootfs_qcom-msm89x7/boot/* && find postmarketos-qcom-msm89x7/ -print | zip postmarketos-qcom-msm89x7.${{ env.stamp }}.zip -@
    - name: Create GH release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: true
        prerelease: false
        release_name: postmarketos--${{ env.stamp }}
        tag_name: ${{ env.stamp }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Upload zipped image to release artifacts
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: postmarketos-qcom-msm89x7.${{ env.stamp }}.zip
        asset_name: postmarketos-qcom-msm89x7.${{ env.stamp }}.zip
        asset_content_type: application/zip
